intall-dependencies:
	@./scripts/ci_run_docker_build.sh npm install

tests:intall-dependencies
	@./scripts/ci_run_docker_build.sh npm run test:ci

tests:
	@./scripts/ci_run_docker_build.sh npm run test:ci

publish:
	@./scripts/ci_run_docker_build.sh ./scripts/docker_build_and_push.sh ${BUILD_NUMBER}